Models/ViewModels/OperadorasViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace Laboratorio.Models.ViewModels
{
    public class OperadorasViewModel
    {
        [Required]
        [Display(Name = "Ingrese el nombre")]
        [StringLength(60, MinimumLength = 3)]
        public string Nombre { get; set; }

        [Required]
        [Display(Name = "Ingrese el anio")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "int(18, 2)")]
        public int Anio { get; set; }

    }

    public class EditarOperadorasViewModel
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Ingrese el nombre")]
        [StringLength(60, MinimumLength = 3)]
        public string Nombre { get; set; }

        [Required]
        [Display(Name = "Ingrese el anio")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "int(18, 2)")]
        public int Anio { get; set; }
    }
}

Controllers/OperadorasController.cs
using Laboratorio.Models.TableViewModels;
using Laboratorio.Models.ViewModels;
using Laboratorio.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laboratorio.Controllers
{
    public class OperadorasController : Controller
    {
        // GET: Marca
        public ActionResult Index()
        {
            List<OperadorasTableViewModels> lst = null;

            using (db_celularesEntities db = new db_celularesEntities())
            {
                lst = (from d in db.tbl_operadora
                       select new OperadorasTableViewModels
                       {
                           Id = d.id,
                           Nombre = d.nombre,
                           Anio = (int)d.anio
                       }).ToList();
            }
            return View(lst);
        }

        [HttpGet]
        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(OperadorasViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            using (db_celularesEntities db = new db_celularesEntities())
            {
                tbl_operadora oOperadora = new tbl_operadora();

                oOperadora.nombre = model.Nombre;
                oOperadora.anio = model.Anio;

                db.tbl_operadora.Add(oOperadora);
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Operadoras/"));
        }

        public ActionResult Editar(int id)
        {
            EditarOperadorasViewModel model = new EditarOperadorasViewModel();

            using (db_celularesEntities db = new db_celularesEntities())
            {
                var oOperadora = db.tbl_operadora.Find(id);

                model.Id = oOperadora.id;
                model.Nombre = oOperadora.nombre;
                model.Anio = (int)oOperadora.anio;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(EditarOperadorasViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            using (db_celularesEntities db = new db_celularesEntities())
            {
                var oOperadora = db.tbl_operadora.Find(model.Id);
                oOperadora.nombre = model.Nombre;
                oOperadora.anio = model.Anio;
                db.Entry(oOperadora).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Operadoras/"));
        }


        public ActionResult Eliminar(int id)
        {
            using (db_celularesEntities db = new db_celularesEntities())
            {
                var oOperadora = db.tbl_operadora.Find(id);

                db.tbl_operadora.Remove(oOperadora);
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Operadoras/"));
        }
    }
}

Views/Operadoras/Editar.cshtml
@model Laboratorio.Models.ViewModels.EditarOperadorasViewModel
@{
    ViewBag.Title = "Nueva Operadora";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("Editar", "Operadoras", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(d => d.Id)

            @Html.LabelFor(d => d.Nombre)
            @Html.TextBoxFor(d => d.Nombre, new { @class = "form-control" })
            <div style="color: red;">
                @Html.ValidationMessageFor(model => model.Nombre)
            </div>
            <br /><br />

            @Html.LabelFor(d => d.Anio)
            @Html.TextBoxFor(d => d.Anio, new { @class = "form-control" })
            <div style="color: red;">
                @Html.ValidationMessageFor(model => model.Anio)
            </div>
            <br /><br />
            <div style="text-align: left;">
                <input type="submit" class="btn btn-success" value="Guardar " />
            </div>

        }
    </div>
</div>

Views/Operadoras/Index.cshtml
@model List<Laboratorio.Models.TableViewModels.OperadorasTableViewModels>
@{
    ViewBag.Title = "Operadora";
}

<h2>Operadora</h2>

<div class="row">
    <div class="col-lg-6">
        <table class="table table-striped">
            <tr class="">
                <th>ID</th>
                <th>NOMBRE</th>
                <th>ANIO</th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var oOperadora in Model)
            {
                <tr>
                    <th>@oOperadora.Id</th>
                    <td>@oOperadora.Nombre</td>
                    <td>@oOperadora.Anio</td>
                    <td>
                        <button type="button" class="btn btn-info" onclick="document.location.href = '@Url.Content("~/Operadoras/Editar/"+oOperadora.Id)'">Editar</button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-danger" onclick="document.location.href = '@Url.Content("~/Operadoras/Eliminar/"+oOperadora.Id)'">Eliminar</button>
                    </td>
                </tr>
            }
        </table>
        <div>
        @Html.ActionLink("Nuevo", "Nuevo", "Operadoras")
        </div>
    </div>
</div>


Views/Operadoras/Nuevo.cshtml
@model Laboratorio.Models.ViewModels.OperadorasViewModel
@{
    ViewBag.Title = "Nueva Operadora";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("Nuevo", "Operadoras", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            @Html.LabelFor(d => d.Nombre)
            @Html.TextBoxFor(d => d.Nombre, new { @class = "form-control" })
            <div style="color: red;">
                @Html.ValidationMessageFor(model => model.Nombre)
            </div>
            <br /><br />

            @Html.LabelFor(d => d.Anio)
            @Html.TextBoxFor(d => d.Anio, new { @class = "form-control" })
            <div style="color: red;">
                @Html.ValidationMessageFor(model => model.Anio)
            </div>
            <br /><br />
            <div style="text-align: left;">
                <input type="submit" class="btn btn-success" value="Guardar " />
            </div>

        }
    </div>
</div>