Models/ViewModels/CelularesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;
using System.Web.UI.WebControls;
using System.ComponentModel.DataAnnotations.Schema;

namespace Laboratorio.Models.ViewModels
{
    public class CelularesViewModel
    {
        [Required]
        [Display(Name = "Ingrese el modelo")]
        [StringLength(60, MinimumLength = 3)]
        public string Modelo { get; set; }

        [Required]
        [Display(Name = "Ingrese la marca")]
        [StringLength(60, MinimumLength = 3)]
        public string Marca { get; set; }

        [Required]
        [Display(Name = "Ingrese el Precio")]
        public decimal Precio { get; set; }

        [Required]
        [Display(Name = "Seleccione la Operadora")]
        public int IdOperadora { get; set; }
        public string Operadora { get; set; }
    }

    public class EditarCelularesViewModels
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Ingrese el modelo")]
        [StringLength(60, MinimumLength = 3)]
        public string Modelo { get; set; }

        [Required]
        [Display(Name = "Ingrese la marca")]
        [StringLength(60, MinimumLength = 3)]
        public string Marca { get; set; }

        [Required]
        [Display(Name = "Ingrese el Precio")]
        public decimal Precio { get; set; }

        [Required]
        [Display(Name = "Seleccione la Operadora")]
        public int IdOperadora { get; set; }
        public string Operadora { get; set; }
    }
}

Controllers/CelularesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Laboratorio.Models;
using Laboratorio.Models.TableViewModels;
using Laboratorio.Models.ViewModels;

namespace Laboratorio.Controllers
{
    public class CelularesController : Controller
    {
        // GET: Celulares
        public ActionResult Index()
        {
            List<CelularesTableViewModels> lst = null;
            using (var db = new db_celularesEntities())
            {
                lst = (from p in db.tbl_celulares
                       join
                       g in db.tbl_operadora on
                       p.idOperadora equals g.id
                       select new CelularesTableViewModels
                       {
                           Id = p.id,
                           Modelo = p.modelo,
                           Marca = p.marca,
                           Precio = (decimal)p.precio,
                           Operadora = g.nombre
                       }).ToList();
            }
            return View(lst);
        }
        public void cargarCboxOperadoras()
        {
            List<SelectListItem> ListOpeadoras = null;
            using (var db = new db_celularesEntities())
            {
                ListOpeadoras = (from g in db.tbl_operadora
                                 select new SelectListItem
                                 {
                                     Value = g.id.ToString(),
                                     Text = g.nombre.ToString(),
                                 }).ToList();
            }
            ViewBag.ListOpeadoras = ListOpeadoras;
        }

        [HttpGet]
        public ActionResult Nuevo()
        {
            cargarCboxOperadoras();
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(CelularesViewModel model)
        {
            if (!ModelState.IsValid)
            {
                cargarCboxOperadoras();
                return View(model);
            }
            using (db_celularesEntities db = new db_celularesEntities())
            {
                tbl_celulares oCelular = new tbl_celulares();

                oCelular.modelo = model.Modelo;
                oCelular.marca = model.Marca;
                oCelular.precio = model.Precio;
                oCelular.idOperadora = model.IdOperadora;

                db.tbl_celulares.Add(oCelular);
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Celulares/"));
        }

        public ActionResult Editar(int id)
        {
            cargarCboxOperadoras();
            EditarCelularesViewModels model = new EditarCelularesViewModels();

            using (db_celularesEntities db = new db_celularesEntities())
            {
                var oCelular = db.tbl_celulares.Find(id);

                model.Id = oCelular.id;
                model.Marca = oCelular.marca;
                model.Modelo = oCelular.modelo;
                model.Precio = (decimal)oCelular.precio;
                model.IdOperadora = (int)oCelular.idOperadora;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(EditarCelularesViewModels model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            using (db_celularesEntities db = new db_celularesEntities())
            {
                var oCelular = db.tbl_celulares.Find(model.Id);
                oCelular.modelo = model.Modelo;
                oCelular.marca = model.Marca;
                oCelular.precio = model.Precio;
                oCelular.idOperadora = model.IdOperadora;
                db.Entry(oCelular).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Celulares/"));
        }
        public ActionResult Eliminar(int id)
        {
            using (db_celularesEntities db = new db_celularesEntities())
            {
                var oCelular = db.tbl_celulares.Find(id);

                db.tbl_celulares.Remove(oCelular);
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Celulares/"));
        }
    }
}

Views/Celulares/Editar.cshtml
@model Laboratorio.Models.ViewModels.EditarCelularesViewModels
@{
    ViewBag.Title = "Editar Celular";
    List<SelectListItem> listOperadora = (List<SelectListItem>)ViewBag.ListOpeadoras;
}

<h2>@ViewBag.Title</h2>
<br />
<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("Editar", "Celulares", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(d => d.Id)

            @Html.LabelFor(d => d.Marca)
            @Html.TextBoxFor(d => d.Marca, new { @class = "form-control" })
            <div style="color: red;">
                @Html.ValidationMessageFor(model => model.Marca)
            </div>
            <br /><br />

            @Html.LabelFor(d => d.Modelo)
            @Html.TextBoxFor(d => d.Modelo, new { @class = "form-control" })
            <div style="color: red;">
                @Html.ValidationMessageFor(model => model.Modelo)
            </div>
            <br /><br />

            @Html.LabelFor(d => d.Precio)
            @Html.TextBoxFor(d => d.Precio, new { @class = "form-control" })
            <div style="color: red;">
                @Html.ValidationMessageFor(model => model.Precio)
            </div>
            <br /><br />

            @Html.LabelFor(d => d.Operadora)
            @Html.DropDownList("idOperadora", listOperadora, null, new { @class = "form-control" })


            <br /><br />
            <div style="text-align: left;">
                <input type="submit" class="btn btn-success" value="Guardar " />
            </div>

        }
    </div>
</div>

Views/Celulares/Index.cshtml
@model List<Laboratorio.Models.TableViewModels.CelularesTableViewModels>
@{
    ViewBag.Title = "Celulares";
}
<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-lg-6">
        <table class="table table-striped">
            <tr class="">
                <th>ID</th>
                <th>MODELO</th>
                <th>MARCA</th>
                <th>PRECIO</th>
                <th>OPERADORA</th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var oCelular in Model)
            {
                <tr>
                    <th>@oCelular.Id</th>
                    <td>@oCelular.Modelo</td>
                    <td>@oCelular.Marca</td>
                    <td>@oCelular.Precio</td>
                    <td>@oCelular.Operadora</td>
                    <td>
                        <button type="button" class="btn btn-info" onclick="document.location.href = '@Url.Content("~/Celulares/Editar/"+oCelular.Id)'">Editar</button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-danger" onclick="document.location.href = '@Url.Content("~/Celulares/Eliminar/"+oCelular.Id)'">Eliminar</button>
                    </td>
                </tr>
            }
        </table>
        <div>
            @Html.ActionLink("Nuevo", "Nuevo", "Celulares")
        </div>
    </div>
</div>

Views/Celulares/Nuevo.cshtml
@model Laboratorio.Models.ViewModels.CelularesViewModel
@{
    ViewBag.Title = "Nuevo Celular";
    List<SelectListItem> listOperadora = (List<SelectListItem>)ViewBag.ListOpeadoras;
}

<h2>@ViewBag.Title</h2>
<br />
<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("Nuevo", "Celulares", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            @Html.LabelFor(d => d.Marca)
            @Html.TextBoxFor(d => d.Marca, new { @class = "form-control" })
            <div style="color: red;">
                @Html.ValidationMessageFor(model => model.Marca)
            </div>
            <br /><br />

            @Html.LabelFor(d => d.Modelo)
            @Html.TextBoxFor(d => d.Modelo, new { @class = "form-control" })
            <div style="color: red;">
                @Html.ValidationMessageFor(model => model.Modelo)
            </div>
            <br /><br />

            @Html.LabelFor(d => d.Precio)
            @Html.TextBoxFor(d => d.Precio, new { @class = "form-control" })
            <div style="color: red;">
                @Html.ValidationMessageFor(model => model.Precio)
            </div>
            <br /><br />

            @Html.LabelFor(d => d.Operadora)
            @Html.DropDownList("idOperadora", listOperadora, null, new { @class = "form-control" })


            <br /><br />
            <div style="text-align: left;">
                <input type="submit" class="btn btn-success" value="Guardar " />
            </div>

        }
    </div>
</div>